[2024-03-26 17:33:46,521] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:46,538] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:46,538] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:46,538] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:33:46,538] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:46,743] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2022-01-02 06:00:00+00:00
[2024-03-26 17:33:46,752] {standard_task_runner.py:52} INFO - Started process 2824 to run task
[2024-03-26 17:33:46,767] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '408', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpmjt0mfgx', '--error-file', '/tmp/tmp90nznsw9']
[2024-03-26 17:33:46,768] {standard_task_runner.py:77} INFO - Job 408: Subtask ingest_to_postgres_task
[2024-03-26 17:33:47,177] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [running]> on host d71984e59113
[2024-03-26 17:33:47,689] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:33:47,966] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2024-03-26 17:33:47,967] {logging_mixin.py:109} INFO - yellow_taxi_2022_01 /opt/***/yellowtaxi_tripdata_2022-01.parquet 2022-01-02T06:00:00+00:00
[2024-03-26 17:33:47,967] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 17:33:47,993] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 7, saw 9

[2024-03-26 17:33:48,113] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=ingest_to_postgres_task, execution_date=20220102T060000, start_date=20240326T173346, end_date=20240326T173348
[2024-03-26 17:33:48,424] {standard_task_runner.py:92} ERROR - Failed to execute job 408 for task ingest_to_postgres_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 7, saw 9

[2024-03-26 17:33:48,466] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 17:33:48,775] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:48:34,347] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:34,387] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:34,387] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:34,388] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:48:34,388] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:34,451] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2022-01-02 06:00:00+00:00
[2024-03-26 17:48:34,459] {standard_task_runner.py:52} INFO - Started process 240 to run task
[2024-03-26 17:48:34,470] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '489', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpoirsikkq', '--error-file', '/tmp/tmpzu4gpulf']
[2024-03-26 17:48:34,471] {standard_task_runner.py:77} INFO - Job 489: Subtask ingest_to_postgres_task
[2024-03-26 17:48:34,636] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:48:34,804] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:48:34,859] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2024-03-26 17:48:34,861] {logging_mixin.py:109} INFO - yellow_taxi_2022_01 /opt/***/yellowtaxi_tripdata_2022-01.parquet 2022-01-02T06:00:00+00:00
[2024-03-26 17:48:34,861] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 17:48:34,900] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 7, saw 9

[2024-03-26 17:48:34,936] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=ingest_to_postgres_task, execution_date=20220102T060000, start_date=20240326T174834, end_date=20240326T174834
[2024-03-26 17:48:34,993] {standard_task_runner.py:92} ERROR - Failed to execute job 489 for task ingest_to_postgres_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 7, saw 9

[2024-03-26 17:48:35,047] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 17:48:35,181] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:52:10,440] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:10,465] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:10,465] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:10,466] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:52:10,466] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:10,483] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2022-01-02 06:00:00+00:00
[2024-03-26 17:52:10,491] {standard_task_runner.py:52} INFO - Started process 665 to run task
[2024-03-26 17:52:10,497] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '567', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpa_46mn_w', '--error-file', '/tmp/tmpjvn_7tg_']
[2024-03-26 17:52:10,498] {standard_task_runner.py:77} INFO - Job 567: Subtask ingest_to_postgres_task
[2024-03-26 17:52:10,609] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:52:10,672] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:52:10,702] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2024-03-26 17:52:10,704] {logging_mixin.py:109} INFO - yellow_taxi_2022_01 /opt/***/yellowtaxi_tripdata_2022-01.parquet 2022-01-02T06:00:00+00:00
[2024-03-26 17:52:10,704] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 17:52:10,732] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 7, saw 9

[2024-03-26 17:52:10,758] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=ingest_to_postgres_task, execution_date=20220102T060000, start_date=20240326T175210, end_date=20240326T175210
[2024-03-26 17:52:10,778] {standard_task_runner.py:92} ERROR - Failed to execute job 567 for task ingest_to_postgres_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 7, saw 9

[2024-03-26 17:52:10,789] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 17:52:10,825] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 18:03:27,283] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-26 18:03:27,469] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-26 18:03:27,476] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:03:27,483] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 18:03:27,487] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:03:27,805] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2022-01-02 06:00:00+00:00
[2024-03-26 18:03:27,939] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '643', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpm6gp5jbk', '--error-file', '/tmp/tmpfdmy8isx']
[2024-03-26 18:03:27,941] {standard_task_runner.py:77} INFO - Job 643: Subtask ingest_to_postgres_task
[2024-03-26 18:03:27,922] {standard_task_runner.py:52} INFO - Started process 1510 to run task
[2024-03-26 18:03:28,744] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 18:03:29,218] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 18:03:29,450] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2024-03-26 18:03:29,460] {logging_mixin.py:109} INFO - yellow_taxi_2022_01 /opt/***/yellowtaxi_tripdata_2022-01.parquet 2022-01-02T06:00:00+00:00
[2024-03-26 18:03:29,478] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 18:03:38,035] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2022_01 in the database...
[2024-03-27 02:48:05,491] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-27 02:48:05,689] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-27 02:48:05,689] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 02:48:05,690] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-27 02:48:05,690] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 02:48:05,977] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2022-01-02 06:00:00+00:00
[2024-03-27 02:48:06,067] {standard_task_runner.py:52} INFO - Started process 1461 to run task
[2024-03-27 02:48:06,116] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '749', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpr4_6f3s7', '--error-file', '/tmp/tmp18_83hr9']
[2024-03-27 02:48:06,117] {standard_task_runner.py:77} INFO - Job 749: Subtask ingest_to_postgres_task
[2024-03-27 02:48:06,843] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-27 02:48:07,547] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-27 02:48:07,712] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2024-03-27 02:48:07,714] {logging_mixin.py:109} INFO - yellow_taxi_2022_01 /opt/***/yellowtaxi_tripdata_2022-01.parquet 2022-01-02T06:00:00+00:00
[2024-03-27 02:48:07,727] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-27 02:48:18,743] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2022_01 in the database...
[2024-03-28 01:58:50,039] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-28 01:58:50,078] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-28 01:58:50,079] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 01:58:50,079] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 01:58:50,080] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 01:58:50,109] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2022-01-02 06:00:00+00:00
[2024-03-28 01:58:50,120] {standard_task_runner.py:52} INFO - Started process 877 to run task
[2024-03-28 01:58:50,150] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '828', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpkghmh782', '--error-file', '/tmp/tmpssdnarm9']
[2024-03-28 01:58:50,152] {standard_task_runner.py:77} INFO - Job 828: Subtask ingest_to_postgres_task
[2024-03-28 01:58:50,703] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 01:58:51,118] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 01:58:51,270] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2024-03-28 01:58:51,274] {logging_mixin.py:109} INFO - yellow_taxi_2022_01 /opt/***/yellowtaxi_tripdata_2022-01.parquet 2022-01-02T06:00:00+00:00
[2024-03-28 01:58:51,275] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-28 01:58:57,152] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2022_01 in the database...
[2024-03-28 09:01:45,514] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-28 09:01:45,656] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-28 09:01:45,658] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 09:01:45,670] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 09:01:45,670] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 09:01:45,762] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2022-01-02 06:00:00+00:00
[2024-03-28 09:01:45,831] {standard_task_runner.py:52} INFO - Started process 643 to run task
[2024-03-28 09:01:45,905] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '969', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp393isge1', '--error-file', '/tmp/tmpt41sqiqh']
[2024-03-28 09:01:46,011] {standard_task_runner.py:77} INFO - Job 969: Subtask ingest_to_postgres_task
[2024-03-28 09:01:46,409] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 09:01:46,691] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 09:01:46,962] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2024-03-28 09:01:46,964] {logging_mixin.py:109} INFO - yellow_taxi_2022_01 /opt/***/yellowtaxi_tripdata_2022-01.parquet 2022-01-02T06:00:00+00:00
[2024-03-28 09:01:46,964] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-28 09:01:59,166] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2022_01 in the database...
[2024-03-28 10:08:10,152] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-28 10:08:10,289] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [queued]>
[2024-03-28 10:08:10,290] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 10:08:10,290] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 10:08:10,290] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 10:08:10,609] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2022-01-02 06:00:00+00:00
[2024-03-28 10:08:10,617] {standard_task_runner.py:52} INFO - Started process 567 to run task
[2024-03-28 10:08:10,696] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2022-01-02T06:00:00+00:00', '--job-id', '1136', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpjfiqxni8', '--error-file', '/tmp/tmp7zg7wo1p']
[2024-03-28 10:08:10,697] {standard_task_runner.py:77} INFO - Job 1136: Subtask ingest_to_postgres_task
[2024-03-28 10:08:12,046] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2022-01-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 10:08:12,496] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 10:08:13,053] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-02T06:00:00+00:00
[2024-03-28 10:08:13,055] {logging_mixin.py:109} INFO - yellow_taxi_2022_01 /opt/***/yellowtaxi_tripdata_2022-01.parquet 2022-01-02T06:00:00+00:00
[2024-03-28 10:08:13,055] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-28 10:08:23,417] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2022_01 in the database...
