[2024-03-26 17:33:44,804] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:44,912] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:44,914] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:44,916] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:33:44,916] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:44,964] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2021-08-02 06:00:00+00:00
[2024-03-26 17:33:44,982] {standard_task_runner.py:52} INFO - Started process 2820 to run task
[2024-03-26 17:33:45,002] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmphkx2d382', '--error-file', '/tmp/tmpnw9iuw96']
[2024-03-26 17:33:45,003] {standard_task_runner.py:77} INFO - Job 405: Subtask ingest_to_postgres_task
[2024-03-26 17:33:45,220] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [running]> on host d71984e59113
[2024-03-26 17:33:45,415] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:33:45,469] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2024-03-26 17:33:45,471] {logging_mixin.py:109} INFO - yellow_taxi_2021_08 /opt/***/yellowtaxi_tripdata_2021-08.parquet 2021-08-02T06:00:00+00:00
[2024-03-26 17:33:45,471] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 17:33:45,530] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 9, saw 7

[2024-03-26 17:33:45,585] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=ingest_to_postgres_task, execution_date=20210802T060000, start_date=20240326T173344, end_date=20240326T173345
[2024-03-26 17:33:45,639] {standard_task_runner.py:92} ERROR - Failed to execute job 405 for task ingest_to_postgres_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 9, saw 7

[2024-03-26 17:33:45,694] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 17:33:45,759] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:48:32,126] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:32,253] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:32,260] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:32,261] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:48:32,263] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:32,354] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2021-08-02 06:00:00+00:00
[2024-03-26 17:48:32,406] {standard_task_runner.py:52} INFO - Started process 232 to run task
[2024-03-26 17:48:32,448] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '483', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpwxz9ldz1', '--error-file', '/tmp/tmp9akrcm7l']
[2024-03-26 17:48:32,448] {standard_task_runner.py:77} INFO - Job 483: Subtask ingest_to_postgres_task
[2024-03-26 17:48:32,696] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:48:32,901] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:48:33,026] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2024-03-26 17:48:33,028] {logging_mixin.py:109} INFO - yellow_taxi_2021_08 /opt/***/yellowtaxi_tripdata_2021-08.parquet 2021-08-02T06:00:00+00:00
[2024-03-26 17:48:33,029] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 17:48:33,100] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 9, saw 7

[2024-03-26 17:48:33,156] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=ingest_to_postgres_task, execution_date=20210802T060000, start_date=20240326T174832, end_date=20240326T174833
[2024-03-26 17:48:33,209] {standard_task_runner.py:92} ERROR - Failed to execute job 483 for task ingest_to_postgres_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 9, saw 7

[2024-03-26 17:48:33,258] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 17:48:33,345] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:52:08,082] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:08,210] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:08,211] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:08,211] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:52:08,211] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:08,291] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2021-08-02 06:00:00+00:00
[2024-03-26 17:52:08,323] {standard_task_runner.py:52} INFO - Started process 659 to run task
[2024-03-26 17:52:08,355] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '561', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpohfkp1m7', '--error-file', '/tmp/tmpsx5yy07d']
[2024-03-26 17:52:08,356] {standard_task_runner.py:77} INFO - Job 561: Subtask ingest_to_postgres_task
[2024-03-26 17:52:08,624] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:52:08,708] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:52:08,768] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2024-03-26 17:52:08,769] {logging_mixin.py:109} INFO - yellow_taxi_2021_08 /opt/***/yellowtaxi_tripdata_2021-08.parquet 2021-08-02T06:00:00+00:00
[2024-03-26 17:52:08,769] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 17:52:08,797] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 9, saw 7

[2024-03-26 17:52:08,820] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=ingest_to_postgres_task, execution_date=20210802T060000, start_date=20240326T175208, end_date=20240326T175208
[2024-03-26 17:52:08,853] {standard_task_runner.py:92} ERROR - Failed to execute job 561 for task ingest_to_postgres_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 22, in ingest_callable
    df = pd.read_csv(parquet_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 9, saw 7

[2024-03-26 17:52:08,900] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 17:52:08,976] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 18:02:46,896] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 18:02:47,003] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 18:02:47,003] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:02:47,003] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 18:02:47,003] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:02:47,073] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2021-08-02 06:00:00+00:00
[2024-03-26 18:02:47,104] {standard_task_runner.py:52} INFO - Started process 1395 to run task
[2024-03-26 18:02:47,143] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '633', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpd_o8008d', '--error-file', '/tmp/tmprrkwufqk']
[2024-03-26 18:02:47,144] {standard_task_runner.py:77} INFO - Job 633: Subtask ingest_to_postgres_task
[2024-03-26 18:02:47,415] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 18:02:47,553] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 18:02:47,612] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2024-03-26 18:02:47,614] {logging_mixin.py:109} INFO - yellow_taxi_2021_08 /opt/***/yellowtaxi_tripdata_2021-08.parquet 2021-08-02T06:00:00+00:00
[2024-03-26 18:02:47,614] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 18:02:52,517] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2021_08 in the database...
[2024-03-27 02:48:04,835] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-27 02:48:04,895] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-27 02:48:04,896] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 02:48:04,896] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-27 02:48:04,897] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 02:48:04,981] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2021-08-02 06:00:00+00:00
[2024-03-27 02:48:05,047] {standard_task_runner.py:52} INFO - Started process 1452 to run task
[2024-03-27 02:48:05,071] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '746', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpyldsv3g1', '--error-file', '/tmp/tmphl0exsvl']
[2024-03-27 02:48:05,073] {standard_task_runner.py:77} INFO - Job 746: Subtask ingest_to_postgres_task
[2024-03-27 02:48:05,901] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-27 02:48:06,242] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-27 02:48:06,403] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2024-03-27 02:48:06,405] {logging_mixin.py:109} INFO - yellow_taxi_2021_08 /opt/***/yellowtaxi_tripdata_2021-08.parquet 2021-08-02T06:00:00+00:00
[2024-03-27 02:48:06,405] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-27 02:48:18,759] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2021_08 in the database...
[2024-03-28 01:58:46,120] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-28 01:58:46,261] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-28 01:58:46,272] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 01:58:46,273] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 01:58:46,276] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 01:58:46,531] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest_to_postgres_task> on 2021-08-02 06:00:00+00:00
[2024-03-28 01:58:46,540] {standard_task_runner.py:52} INFO - Started process 846 to run task
[2024-03-28 01:58:46,594] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'ingest_to_postgres_task', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '824', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpf1dku6uo', '--error-file', '/tmp/tmpbft2kbl9']
[2024-03-28 01:58:46,623] {standard_task_runner.py:77} INFO - Job 824: Subtask ingest_to_postgres_task
[2024-03-28 01:58:47,248] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.ingest_to_postgres_task scheduled__2021-08-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 01:58:47,880] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 01:58:48,077] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=ingest_to_postgres_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2024-03-28 01:58:48,079] {logging_mixin.py:109} INFO - yellow_taxi_2021_08 /opt/***/yellowtaxi_tripdata_2021-08.parquet 2021-08-02T06:00:00+00:00
[2024-03-28 01:58:48,079] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-28 01:58:54,185] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2021_08 in the database...
