[2024-03-30 03:54:10,756] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 03:54:10,773] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 03:54:10,774] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 03:54:10,775] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 03:54:10,775] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 03:54:10,794] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 06:00:00+00:00
[2024-03-30 03:54:10,803] {standard_task_runner.py:52} INFO - Started process 2269 to run task
[2024-03-30 03:54:10,808] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-12-02T06:00:00+00:00', '--job-id', '2030', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpoa4jfr6e', '--error-file', '/tmp/tmpr06fffrp']
[2024-03-30 03:54:10,815] {standard_task_runner.py:77} INFO - Job 2030: Subtask local_to_gcs_task
[2024-03-30 03:54:10,903] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 03:54:10,959] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 03:54:10,986] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-02T06:00:00+00:00
[2024-03-30 03:54:11,528] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_12.parquet.
[2024-03-30 03:54:11,529] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 03:54:11,551] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20231202T060000, start_date=20240330T035410, end_date=20240330T035411
[2024-03-30 03:54:11,593] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 03:54:11,908] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30 04:26:18,339] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:26:18,375] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:26:18,375] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:26:18,375] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 04:26:18,375] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:26:18,408] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 06:00:00+00:00
[2024-03-30 04:26:18,417] {standard_task_runner.py:52} INFO - Started process 4567 to run task
[2024-03-30 04:26:18,432] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-12-02T06:00:00+00:00', '--job-id', '2256', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp2wfncowt', '--error-file', '/tmp/tmpcn57454h']
[2024-03-30 04:26:18,463] {standard_task_runner.py:77} INFO - Job 2256: Subtask local_to_gcs_task
[2024-03-30 04:26:18,588] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 04:26:18,655] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 04:26:18,693] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-02T06:00:00+00:00
[2024-03-30 04:26:19,325] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_12.parquet.
[2024-03-30 04:26:19,326] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 04:26:19,342] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20231202T060000, start_date=20240330T042618, end_date=20240330T042619
[2024-03-30 04:26:19,391] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 04:26:19,446] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 04:45:13,812] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:45:13,883] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:45:13,883] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:45:13,884] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 04:45:13,884] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:45:13,964] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 06:00:00+00:00
[2024-03-30 04:45:14,004] {standard_task_runner.py:52} INFO - Started process 5877 to run task
[2024-03-30 04:45:14,086] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-12-02T06:00:00+00:00', '--job-id', '2379', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpbg39s7wc', '--error-file', '/tmp/tmpu7xy_l94']
[2024-03-30 04:45:14,099] {standard_task_runner.py:77} INFO - Job 2379: Subtask local_to_gcs_task
[2024-03-30 04:45:14,438] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 04:45:14,579] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 04:45:14,653] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-02T06:00:00+00:00
[2024-03-30 04:45:15,497] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_12.parquet.
[2024-03-30 04:45:15,497] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 04:45:15,528] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20231202T060000, start_date=20240330T044513, end_date=20240330T044515
[2024-03-30 04:45:15,651] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 04:45:15,762] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 05:00:52,872] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 05:00:52,927] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 05:00:52,928] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 05:00:52,928] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 05:00:52,928] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 05:00:52,994] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 06:00:00+00:00
[2024-03-30 05:00:53,014] {standard_task_runner.py:52} INFO - Started process 7018 to run task
[2024-03-30 05:00:53,055] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-12-02T06:00:00+00:00', '--job-id', '2502', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpvkplvnek', '--error-file', '/tmp/tmpvpoyms9u']
[2024-03-30 05:00:53,086] {standard_task_runner.py:77} INFO - Job 2502: Subtask local_to_gcs_task
[2024-03-30 05:00:53,343] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 05:00:53,532] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 05:00:53,619] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-02T06:00:00+00:00
[2024-03-30 05:00:54,873] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_12.parquet.
[2024-03-30 05:00:54,873] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 05:00:54,901] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20231202T060000, start_date=20240330T050052, end_date=20240330T050054
[2024-03-30 05:00:54,988] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 05:00:55,081] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 09:03:36,016] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 09:03:36,063] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 09:03:36,063] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 09:03:36,064] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 09:03:36,064] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 09:03:36,086] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 06:00:00+00:00
[2024-03-30 09:03:36,104] {standard_task_runner.py:52} INFO - Started process 18558 to run task
[2024-03-30 09:03:36,125] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-12-02T06:00:00+00:00', '--job-id', '2616', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpyz0st9iv', '--error-file', '/tmp/tmprq6dshia']
[2024-03-30 09:03:36,140] {standard_task_runner.py:77} INFO - Job 2616: Subtask local_to_gcs_task
[2024-03-30 09:03:36,259] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 09:03:36,343] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 09:03:36,437] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-02T06:00:00+00:00
[2024-03-30 09:03:37,098] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_12.parquet.
[2024-03-30 09:03:37,098] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 09:03:37,137] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20231202T060000, start_date=20240330T090336, end_date=20240330T090337
[2024-03-30 09:03:37,239] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 09:03:37,308] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 12:07:43,259] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 12:07:43,274] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-03-30 12:07:43,275] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 12:07:43,275] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 12:07:43,275] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 12:07:43,291] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 06:00:00+00:00
[2024-03-30 12:07:43,304] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-12-02T06:00:00+00:00', '--job-id', '2945', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp4pm9hy_0', '--error-file', '/tmp/tmpopymz0wi']
[2024-03-30 12:07:43,309] {standard_task_runner.py:77} INFO - Job 2945: Subtask local_to_gcs_task
[2024-03-30 12:07:43,299] {standard_task_runner.py:52} INFO - Started process 29524 to run task
[2024-03-30 12:07:43,406] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 12:07:43,450] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 12:07:43,477] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-02T06:00:00+00:00
[2024-03-30 12:07:45,592] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 68, in upload_to_gcs
    df.to_parquet(clean_file_name, index=False)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2372, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 101, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
  File "pyarrow/table.pxi", line 1561, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 607, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 581, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 575, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 302, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column store_and_fwd_flag with type object')
[2024-03-30 12:07:45,609] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20231202T060000, start_date=20240330T120743, end_date=20240330T120745
[2024-03-30 12:07:45,767] {standard_task_runner.py:92} ERROR - Failed to execute job 2945 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 68, in upload_to_gcs
    df.to_parquet(clean_file_name, index=False)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2372, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 101, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
  File "pyarrow/table.pxi", line 1561, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 607, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 581, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 575, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 302, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column store_and_fwd_flag with type object')
[2024-03-30 12:07:45,790] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-30 12:07:45,830] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30 03:02:38,247] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-04-30 03:02:38,302] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-04-30 03:02:38,314] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 03:02:38,314] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-04-30 03:02:38,320] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 03:02:38,361] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 06:00:00+00:00
[2024-04-30 03:02:38,386] {standard_task_runner.py:52} INFO - Started process 1078 to run task
[2024-04-30 03:02:38,410] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-12-02T06:00:00+00:00', '--job-id', '3227', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpv3jqw1_r', '--error-file', '/tmp/tmpzfoj9b30']
[2024-04-30 03:02:38,424] {standard_task_runner.py:77} INFO - Job 3227: Subtask local_to_gcs_task
[2024-04-30 03:02:38,661] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [running]> on host 02dc49e0e362
[2024-04-30 03:02:38,788] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-30 03:02:38,861] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-02T06:00:00+00:00
[2024-04-30 03:02:39,530] {python.py:175} INFO - Done. Returned value was: None
[2024-04-30 03:02:39,629] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20231202T060000, start_date=20240430T030238, end_date=20240430T030239
[2024-04-30 03:02:39,732] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-04-30 03:02:40,010] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30 04:35:42,955] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-04-30 04:35:42,998] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [queued]>
[2024-04-30 04:35:42,999] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 04:35:42,999] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-04-30 04:35:43,000] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 04:35:43,030] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-12-02 06:00:00+00:00
[2024-04-30 04:35:43,047] {standard_task_runner.py:52} INFO - Started process 5937 to run task
[2024-04-30 04:35:43,080] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-12-02T06:00:00+00:00', '--job-id', '3328', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp9x8ho8vs', '--error-file', '/tmp/tmpnz292i6f']
[2024-04-30 04:35:43,089] {standard_task_runner.py:77} INFO - Job 3328: Subtask local_to_gcs_task
[2024-04-30 04:35:43,231] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-12-02T06:00:00+00:00 [running]> on host 02dc49e0e362
[2024-04-30 